export const studentData = [
  {
    field: "Primary Details",
    data: [
      {
        label: "Student Name",
        type: "string",
        placeholder: "Enter name",
        required: "y",
        id: "studentName",
      },
      {
        label: "Date Of Birth",
        type: "date",
        placeholder: "Date of birth",
        required: "y",
        id: "dob",
      },
      {
        label: "Roll Number",
        type: "number",
        placeholder: "Enter roll number",
        required: "y",
        id: "rollNumber",
      },
      {
        label: "Grade",
        type: "number",
        placeholder: "Enter grade",
        required: "y",
        id: "grade",
      },
      {
        label: "Section",
        type: "string",
        placeholder: "Enter Section",
        required: "y",
        id: "section",
      },

      {
        label: "Email Id",
        type: "string",
        placeholder: "email id",
        required: "y",
        id: "email",
      },
    ],
  },
  {
    field: "Personal Details",
    data: [
      {
        label: "Religion",
        type: "string",
        placeholder: "Enter religion",
        required: "y",
        id: "religion",
      },
      {
        label: "Caste",
        type: "string",
        placeholder: "Enter caste",
        required: "y",
        id: "caste",
      },
      {
        label: "Nationality",
        type: "string",
        placeholder: "Enter nationality",
        required: "y",
        id: "nationality",
      },
      {
        label: "Aadhar Number",
        type: "number",
        placeholder: "Enter aadhar number",
        required: "y",
        id: "aadharNumber",
      },
      {
        label: "Gender",
        type: "dropdown",
        placeholder: ["male", "female"],
        required: "y",
        id: "gender",
      },
    ],
  },
  {
    field: "Paternal Details",
    data: [
      {
        label: "Father's Name",
        type: "string",
        placeholder: "Enter name",
        required: "y",
        id: "fatherName",
      },
      {
        label: "Residential Address",
        type: "string",
        placeholder: "Enter current Address",
        required: "y",
        id: "currentAddress",
      },
      {
        label: "Office Address",
        type: "string",
        placeholder: "Enter office address",
        required: "y",
        id: "officeAddress",
      },
      {
        label: "Father's Occupation",
        type: "string",
        placeholder: "Enter occupation",
        required: "y",
        id: "fatherOccupation",
      },
      {
        label: "Education Qualification of Father",
        type: "string",
        placeholder: "Enter education qualification",
        required: "y",
        id: "fatherEducation",
      },
    ],
  },
  {
    field: "Maternal Details",
    data: [
      {
        label: "Mother's Name",
        type: "string",
        placeholder: "Enter name",
        required: "y",
        id: "motherName",
      },
      {
        label: "Mother's Occupation",
        type: "string",
        placeholder: "Enter occupation",
        required: "y",
        id: "motherOccupation",
      },
      {
        label: "Education Qualification of Mother",
        type: "string",
        placeholder: "Enter education qualification",
        required: "y",
        id: "motherEducation",
      },
    ],
  },
  {
    field: "Guardian Details",
    data: [
      {
        label: "Guardian Name",
        type: "string",
        placeholder: "Enter name",
        required: "y",
        id: "guardianName",
      },
      {
        label: "Guardian Address",
        type: "string",
        placeholder: "Enter current Address",
        required: "y",
        id: "guardianAddress",
      },
    ],
  },
  {
    field: "Family Details",
    data: [
      {
        label: "Family Income",
        type: "number",
        placeholder: "Rs per month",
        required: "y",
        id: "familyIncome",
      },
      {
        label: "Primary Contact Number",
        type: "number",
        placeholder: "Enter number",
        required: "y",
        id: "primaryContact",
      },
      {
        label: "Secondary Contact Number",
        type: "number",
        placeholder: "Enter number",
        required: "y",
        id: "secondaryContact",
      },
    ],
  },
  {
    field: "Files",
    data: [
      {
        label: "Upload Aadhar Front Page",
        type: "file",
        placeholder: "",
        required: "y",
        id: "uploadAadharFront",
      },
      {
        label: "Upload Aadhar Back Page",
        type: "file",
        placeholder: "",
        required: "y",
        id: "uploadAadharBack",
      },
      {
        label: "Upload Income Certificate",
        type: "file",
        placeholder: "",
        required: "y",
        id: "uploadIncomeCertificate",
      },
      {
        label: "Upload Birth Certificate",
        type: "file",
        placeholder: "",
        required: "y",
        id: "uploadBirthCertificate",
      },
      {
        label: "Upload Caste Certificate",
        type: "file",
        placeholder: "",
        required: "y",
        id: "uploadCasteCertificate",
      },
    ],
  },
  {
    field: "Non Academic",
    data: [
      {
        label: "Sports Involved",
        type: "string",
        placeholder: "Enter sports activities",
        required: "n",
        id: "sportsInvolved",
      },
      {
        label: "Sports Achievements",
        type: "string",
        placeholder: "Enter sports achievements",
        required: "n",
        id: "sportsAchievements",
      },
      {
        label: "Extra Curricullum activities",
        type: "string",
        placeholder: "Enter extra curricullum activities",
        required: "n",
        id: "extraCurricullum",
      },
      {
        label: "Extra Curricullum achievements",
        type: "string",
        placeholder: "Enter extra curricullum achievements",
        required: "n",
        id: "extraCurricullumAchievements",
      },
      {
        label: "Personality Development Courses",
        type: "string",
        placeholder: "Enter personality development courses",
        required: "n",
        id: "personalityDevelopment",
      },
      {
        label: "Personality development achievements",
        type: "string",
        placeholder: "Enter personality development achievements",
        required: "n",
        id: "personalityDevelopmentAchievements",
      },
    ],
  },
];
